In [4]:
import pandas as pd

env = pd.read_csv('/content/2020_환경_통합_v1.csv', encoding='cp949')
sales = pd.read_csv('/content/2020_판매_통합.csv', encoding='cp949')

In [5]:
print("환경 데이터 크기:", env.shape)
print("판매 데이터 크기:", sales.shape)

환경 데이터 크기: (1048575, 16)
판매 데이터 크기: (39738, 9)

In [6]:
print("환경 데이터 컬럼")
print(env.columns)

print("판매 데이터 컬럼")
print(sales.columns)

환경 데이터 컬럼
Index(['도', '시군', '품목', '작기', '농가명', '측정시간', '온도_외부', '풍향_외부', '풍속_외부',
       '일사량_외부', '누적일사량_외부', '강우감지', '온도_내부', '상대습도_내부', '잔존이산화탄소(CO2)',
       '토양온도'],
      dtype='object')
판매 데이터 컬럼
Index(['도', '시군', '품목', '작기', '농가명', '출하일자', '총출하량', '판매금액', '비고'], dtype='object')

In [7]:
env.head()

,도,시군,품목,작기,농가명,측정시간,온도_외부,풍향_외부,풍속_외부,일사량_외부,누적일사량_외부,강우감지,온도_내부,상대습도_내부,잔존이산화탄소(CO2),토양온도
0,강원,인제,파프리카,1,3,2020-01-30 00:00,0.3,NaN,NaN,0.0,NaN,0,21.1,54.0,346.0,NaN
1,강원,인제,파프리카,1,3,2020-01-30 01:00,0.5,NaN,NaN,0.0,NaN,0,20.5,56.0,346.0,NaN
2,강원,인제,파프리카,1,3,2020-01-30 02:00,0.4,NaN,NaN,0.0,NaN,0,20.6,56.0,346.0,NaN
3,강원,인제,파프리카,1,3,2020-01-30 03:00,0.1,NaN,NaN,0.0,NaN,0,21.2,54.0,346.0,NaN
4,강원,인제,파프리카,1,3,2020-01-30 04:00,0.3,NaN,NaN,0.0,NaN,0,21.7,53.0,346.0,NaN

In [8]:
sales.head()

    도  시군    품목  작기  농가명        출하일자    총출하량  판매금액   비고
0  강원  인제  파프리카   1    3  2020-04-16  1635.0   NaN  NaN
1  강원  인제  파프리카   1    3  2020-04-16   150.0   NaN  NaN
2  강원  인제  파프리카   1    3  2020-04-18  1990.0   NaN  NaN
3  강원  인제  파프리카   1    3  2020-04-18   245.0   NaN  NaN
4  강원  인제  파프리카   1    3  2020-04-21  5100.0   NaN  NaN

In [9]:
#파프리카 데이터만 추출
env_paprika = env[env['품목'] == '파프리카']
sales_paprika = sales[sales['품목'] == '파프리카']

In [10]:
print("파프리카 환경 데이터:", env_paprika.shape)
print("파프리카 판매 데이터:", sales_paprika.shape)

파프리카 환경 데이터: (186266, 16)
파프리카 판매 데이터: (6037, 9)

In [11]:
env_paprika.head()

,도,시군,품목,작기,농가명,측정시간,온도_외부,풍향_외부,풍속_외부,일사량_외부,누적일사량_외부,강우감지,온도_내부,상대습도_내부,잔존이산화탄소(CO2),토양온도
0,강원,인제,파프리카,1,3,2020-01-30 00:00,0.3,NaN,NaN,0.0,NaN,0,21.1,54.0,346.0,NaN
1,강원,인제,파프리카,1,3,2020-01-30 01:00,0.5,NaN,NaN,0.0,NaN,0,20.5,56.0,346.0,NaN
2,강원,인제,파프리카,1,3,2020-01-30 02:00,0.4,NaN,NaN,0.0,NaN,0,20.6,56.0,346.0,NaN
3,강원,인제,파프리카,1,3,2020-01-30 03:00,0.1,NaN,NaN,0.0,NaN,0,21.2,54.0,346.0,NaN
4,강원,인제,파프리카,1,3,2020-01-30 04:00,0.3,NaN,NaN,0.0,NaN,0,21.7,53.0,346.0,NaN

In [12]:
sales_paprika.head()

    도  시군    품목  작기  농가명        출하일자    총출하량  판매금액   비고
0  강원  인제  파프리카   1    3  2020-04-16  1635.0   NaN  NaN
1  강원  인제  파프리카   1    3  2020-04-16   150.0   NaN  NaN
2  강원  인제  파프리카   1    3  2020-04-18  1990.0   NaN  NaN
3  강원  인제  파프리카   1    3  2020-04-18   245.0   NaN  NaN
4  강원  인제  파프리카   1    3  2020-04-21  5100.0   NaN  NaN

In [13]:
#날짜 컬럼 생성
env_paprika['측정시간'] = pd.to_datetime(env_paprika['측정시간'])
sales_paprika['출하일자'] = pd.to_datetime(sales_paprika['출하일자'])

env_paprika['날짜'] = env_paprika['측정시간'].dt.date
sales_paprika['날짜'] = sales_paprika['출하일자'].dt.date

/tmp/ipykernel_2287/3491273482.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  env_paprika['측정시간'] = pd.to_datetime(env_paprika['측정시간'])
/tmp/ipykernel_2287/3491273482.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_paprika['출하일자'] = pd.to_datetime(sales_paprika['출하일자'])
/tmp/ipykernel_2287/3491273482.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  env_paprika['날짜'] = env_paprika['측정시간'].dt.date
/tmp/ipykernel_2287/3491273482.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_paprika['날짜'] = sales_paprika['출하일자'].dt.date

In [14]:
#환경 데이터 일별 집계(시간별 데이터 -> 하루 평균)
env_daily = env_paprika.groupby(
    ['농가명', '날짜']
)[[
    '온도_내부',
    '상대습도_내부',
    '잔존이산화탄소(CO2)',
    '일사량_외부'
]].mean().reset_index()

In [15]:
#판매 데이터 일별 집계
sales_daily = sales_paprika.groupby(
    ['농가명', '날짜']
)['총출하량'].sum().reset_index()

In [16]:
#데이터 병합
data = pd.merge(
    env_daily,
    sales_daily,
    on=['농가명', '날짜']
)

In [17]:
print(data.shape)

data.head()

(1483, 7)

   농가명          날짜      온도_내부    상대습도_내부  잔존이산화탄소(CO2)  일사량_외부    총출하량
0    1  2020-09-01  25.340000  85.340000   1202.200000     NaN  2984.0
1    1  2020-09-02  23.790000  85.590000   1050.100000     NaN   456.0
2    1  2020-09-05  23.108333  83.504167    449.555556     NaN  6024.0
3    1  2020-09-08  24.625000  75.733333    390.333333     NaN  3140.0
4    1  2020-09-09  23.600000  79.400000    423.708333     NaN   642.6

In [18]:
data.isnull().sum()

농가명               0
날짜                0
온도_내부             0
상대습도_내부          84
잔존이산화탄소(CO2)    371
일사량_외부          242
총출하량              0
dtype: int64

In [19]:
data = data.dropna()

In [20]:
X = data[
    [
        '온도_내부',
        '상대습도_내부',
        '잔존이산화탄소(CO2)',
        '일사량_외부'
    ]
]

y = data['총출하량']

In [21]:
print(data.shape)
data.head()

(870, 7)

    농가명          날짜    온도_내부    상대습도_내부  잔존이산화탄소(CO2)     일사량_외부    총출하량
34    2  2020-05-27  22.6375  60.937500    379.875000  42.500000   132.0
35    2  2020-05-29  22.8250  57.166667    295.875000  44.666667   444.0
36    2  2020-06-01  23.4500  57.012500    299.000000  41.833333   774.0
37    2  2020-06-03  24.9500  63.770833    345.142857  39.750000  1368.0
38    2  2020-06-04  24.3000  72.425000    219.500000  32.625000   648.0

In [22]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [23]:
from xgboost import XGBRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

import matplotlib.pyplot as plt

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [25]:
model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    random_state=42
)

In [26]:
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [27]:
pred = model.predict(X_test)

In [28]:
mae = mean_absolute_error(y_test, pred)
r2 = r2_score(y_test, pred)

print("MAE:", mae)
print("R2 Score:", r2)

MAE: 2143.438939794453
R2 Score: 0.06088830790288868

In [32]:
!pip install lightgbm

Requirement already satisfied: lightgbm in /usr/local/lib/python3.12/dist-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from lightgbm) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lightgbm) (1.16.3)

In [33]:
from lightgbm import LGBMRegressor

model2 = LGBMRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    num_leaves=31,
    random_state=42
)

model2.fit(X_train, y_train)

pred = model2.predict(X_test)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000082 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 932
[LightGBM] [Info] Number of data points in the train set: 696, number of used features: 4
[LightGBM] [Info] Start training from score 2115.868966
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [35]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

pred = model2.predict(X_test)

mae = mean_absolute_error(y_test, pred)
r2 = r2_score(y_test, pred)

print("MAE :", mae)
print("R2 Score :", r2)

MAE : 2246.24771621462
R2 Score : 0.05783978340782514